version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: aws-pricing-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: aws-pricing-calculator
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
